### 구현 1) 카테고리 별 최저가격 브랜드와 상품 가격, 총액을 조회하는 API
GET http://localhost:8080/shopping/v1/categories/lowest-price

### 구현 2) 단일 브랜드로 모든 카테고리 상품을 구매할 때 최저가격에 판매하는 브랜드와 카테고리의 상품가격, 총액을 조회하는 API
GET http://localhost:8080/shopping/v1/brand/lowest-price

### 구현 3) 카테고리 이름으로 최저, 최고 가격 브랜드와 상품 가격을 조회하는 API
GET http://localhost:8080/shopping/v1/categories/prices/min-max?
    category_name=상의

### 구현 4) 브랜드 및 상품 추가 API
POST http://localhost:8080/shopping/v1/product
Content-Type: application/json

{
  "brand_name": "J",
  "category_name": "벨트",
  "price": 7000
}

### 구현 5) 브랜드 및 상품 업데이트 API
PATCH http://localhost:8080/shopping/v1/product
Content-Type: application/json

{
  "brand_name": "J",
  "category_name": "벨트",
  "price": 2000
}

### 구현 6) 브랜드 및 상품 삭제 API
DELETE http://localhost:8080/shopping/v1/product
Content-Type: application/json

{
  "brand_name": "J",
  "category_name": "벨트"
}
